// Contains all the "glue" that holds Wayland and River together, primarily generated by
// wayland_scanner.

// Re-exports
pub use interfaces::rwm::*;
pub use interfaces::rxkb::*;
pub extern crate wayland_client;
pub use wayland_client::protocol::*;

// River protocol interfaces
mod interfaces {
    pub(super) mod rwm {
        pub use wayland_client::protocol::__interfaces::*;
        wayland_scanner::generate_interfaces!("protocol/river-window-management-v1.xml");
    }

    pub(super) mod rxkb {
        use super::rwm::*;
        wayland_scanner::generate_interfaces!("protocol/river-xkb-bindings-v1.xml");
    }
}

// River protocol client code
wayland_scanner::generate_client_code!("protocol/river-window-management-v1.xml");
wayland_scanner::generate_client_code!("protocol/river-xkb-bindings-v1.xml");
