// Contains all the "glue" that holds Wayland and River together, primarily generated by
// wayland_scanner.

// Re-exports
pub use self::{
    river_node_v1::RiverNodeV1,
    river_output_v1::RiverOutputV1,
    river_pointer_binding_v1::RiverPointerBindingV1,
    river_seat_v1::{Modifiers, RiverSeatV1},
    river_window_manager_v1::RiverWindowManagerV1,
    river_window_v1::{Edges, RiverWindowV1},
    river_xkb_binding_v1::RiverXkbBindingV1,
    river_xkb_bindings_v1::RiverXkbBindingsV1,
};
pub use interfaces::rwm::*;
pub use interfaces::rxkb::*;
pub use wayland_client::protocol::*;
pub use wayland_client::{Connection, backend::ObjectId};

// Ignore some of the requests River sends for now
wayland_client::delegate_noop!(crate::WindowManager: ignore RiverXkbBindingsV1);
wayland_client::delegate_noop!(crate::WindowManager: ignore RiverNodeV1);

// River protocol interfaces
mod interfaces {
    pub(super) mod rwm {
        pub use wayland_client::protocol::__interfaces::*;
        wayland_scanner::generate_interfaces!("protocol/river-window-management-v1.xml");
    }

    pub(super) mod rxkb {
        use super::rwm::*;
        wayland_scanner::generate_interfaces!("protocol/river-xkb-bindings-v1.xml");
    }
}

// River protocol client code
use wayland_client;
wayland_scanner::generate_client_code!("protocol/river-window-management-v1.xml");
wayland_scanner::generate_client_code!("protocol/river-xkb-bindings-v1.xml");
